<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace GPBMetadata\Proto;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
è
proto/user.protoproto"]
User
Username (	
Password (	
Nickname (	
Birtiday (	
Habby (	BZ.;protodatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

