definitions:
  controllers.Person:
    properties:
      address:
        type: string
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /user/show:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Person'
      summary: Show an account
      tags:
      - accounts
swagger: "2.0"
